name: wallet_app
description: "A Flutter app to digitize your finances."

# The following line prevents the package from being accidentally published to pub.dev
publish_to: "none"

# Version and build number for the application
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Flutter-specific configurations
flutter:
  uses-material-design: true

  # Assets (Images and Icons)
  assets:
    - assets/images/
    - assets/icons/

  # Custom Font (Montserrat)
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 700
